DROP TABLE member IF EXISTS CASCADE;
drop table if exists member_orders CASCADE;
drop table if exists orderinfo CASCADE;

drop sequence if exists hibernate_sequence;
create sequence hibernate_sequence start with 1 increment by 1;


create table member (
   id integer not null,
    email varchar(255),
    gender varchar(255) not null,
    name varchar(255),
    nick_name varchar(255),
    password varchar(255),
    phone_number varchar(255),
    primary key (id)
);

create table member_orders (
   member_id integer not null,
    orders_id bigint not null
);

create table orderinfo (
   id bigint generated by default as identity,
    created_at timestamp,
    last_modified_at timestamp,
    buy_date timestamp,
    product_name varchar(255) not null,
    mem_id integer,
    primary key (id)
);
